### ISSUE TITLE
fuzzy functions

### ISSUE THREAD

**Issue by pickettj** [pickettj/dot_files#4]
Just flagging a few roadblocks on some fuzzy functions workarounds I've been working on (@iamlemec).

Basically, since I have a mounted Box drive, there are just too many files for fuzzy to efficiently sift through. So [these functions](https://github.com/pickettj/dot_files/blob/master/.fzf_functions) help narrow down what I'm looking for.

Most of them work pretty well. But I still can't get the following to work properly:

```
# Fuzzy Create File (in working folder)
## NOT  WORKING
ftf() {
  read -p "File name: " file
  local dir
  dir=$(find $KITOB"Secondary Literature/Pickett library" $KITOB"Secondary Literature/Unsorted Secondary Literature" $KITOB"Primary Sources" -type d | fzf)
  touch $dir/$file
  open $dir/$file
}
```
I.e. I want to enter the name of a file, use fuzzy to quickly find the directory I want to put it in without actually moving to the directory, and then open it.

---

```
# Fuzzy search file contents (current folder)
## NOT WORKING
alias fc="grep --line-buffered --color=never -r "" * | fzf"
```

I want to be able to quickly search through the _contents_ of whatever folder I am currently in; this does not work.

**Comment by iamlemec** [comment]
For the first one, I'd do:
``` zsh
ftf() {
  read "file?File name: "
  local dir
  dir=$(find "${KITOB}/Secondary Literature/Pickett library" "${KITOB}/Secondary Literature/Unsorted Secondary Literature" "${KITOB}/Primary Sources" -type d | fzf)
  touch "${dir}/${file}"
  open "${dir}/${file}"
}
```
I'm assuming `open` is some kind of reasonable alias. Not sure what the error is, but probably coming from spaces in paths, which is why you gotta quote it up.

For the second one, also looks to be space/quote related, I think you can just do:
``` zsh
alias fc="ag . * | fzf"
```
Seems like `ag` will be faster than `grep` here. If you must use `grep`, then:
``` zsh
alias fc="grep --line-buffered --color=never -r . * | fzf"
```

**Comment by pickettj** [comment]
Thanks @iamlemec ! Close, but a few issues still.

Why do you say "I'm assuming open is some kind of reasonable alias." Doesn't `open` just open the path in the default program? But when I replace `open` with `a` (an alias I use to open in Atom), it does seem to work; which I imagine has something to do with why you were asking.

As for the search within content, I'm trying to make it a bit more useful:

```
fc() {
  local file
  file=$(ag . * | fzf --preview 'cat {}' --delimiter / --with-nth -1)
  open "$file"
}
```

The trouble is that it previews just the line with the matching text; and then it is passing the entire line (not just the file name) to `open`. I am trying to figure out how to preview the entire file in the window, and then open it in the default program when I hit enter. (This is pretty much what your Fuzzy app does, but it would be nice to be able to do this in the terminal as well.)

**Comment by iamlemec** [comment]
Yeah, maybe `open` is an OSX thing? The GNU/Linux analog is `xdg-open`.

I think this should work for the file preview. This has line-by-line matches on the left and file preview on the right
```  zsh
fc() {
  local line
  local file
  line=$(ag . * | fzf --preview 'echo {} | cut -d : -f 1 | xargs cat' --delimiter / --with-nth -1)
  file=$(echo $line | cut -d : -f 1)
  open "$file"
}
```
I didn't know about this `--with-nth` stuff, pretty cool!

**Comment by pickettj** [comment]
sweet! got it all working. but may need to talk through some of the logic. do you have any recommended reading for what's going on with `cut -d`, `xargs cat`, or even something like why `"${BOX}/Inbox"` goes inside the brackets?

**Comment by iamlemec** [comment]
Awesome. Yeah, there's a lot of tutorials on shell/bash/zsh scripting in general, but I don't know of any that go into the GNU core commands like these. Maybe the best place to look for reference is just here: https://en.wikipedia.org/wiki/List_of_GNU_Core_Utilities_commands. The general usage of piping (`|`) should be covered in most shell tutorials though. And of course you can always look at the `man` page (for example, run `man xargs`) for these commands.

But actually, just these commands are a pretty good starting point
- `cut`: splits lines by a given delimiter and lets you select a field or fields to return. So you could make a crude CSV selector with this and `-d ,`, though it wouldn't handle quotes or escaping.
- `xargs`: this is pretty handy but not obviously so at first. It'll pass a list of arguments to a given command. So in a case similar to above, instead of writing `cat $(echo file.txt)`, we could write `echo file.txt | xargs cat`. For multiple arguments we could write `echo file1.txt file2.txt | xargs cat`. And if we want them run one at a time, we'd need `echo file1.txt file2.txt | xargs -n 1 cat`.

As for using curly braces on variables. This often isn't strictly necessary, but if you wanted to put a character immediately after a variable, it would be. So if your variable is TEST and you wanted to print TEST immediately followed by "A", then you'd want to run `${TEST}A`. Just running `$TESTA` would look for variable TESTA and print a blank.
