### ISSUE TITLE
fzf lingering issues

### ISSUE THREAD

**Issue by pickettj** [pickettj/dot_files#5]
- How to perform command on multiple files when using ⇧↹?
- How to toggle off the key binding that invokes fzf after ⌘C?

**Comment by pickettj** [comment]
@iamlemec, reading your notes from last time, now I'm thinking that to use fzf to perform a command on multiple files, I'm gonna need to use `xargs`... but I can't quite figure out where to put it:

```
# Fuzzy Move File to Common Working Directories
fmw() {
  local file
  file=$(find . -type f | fzf -m --preview 'cat {}') &&
  local dir
  dir=$(find $TEACH $LANG $PROF $ADMIN $PROJ "${BOX}/Resources and Reference" -type d | fzf)
  mv "$file" "$dir"
}
```

I.e. the `file` local variable can take multiple items, but I need to tell it to use `mv` on each of them individually... currently it will successfully move the first of the files, and then give an error message for the rest:
```
mv: rename ./010-01.pdf
./02634937%2E2011%2E557857.pdf to /Users/enkidu/Box/Teaching/02634937%2E2011%2E557857.pdf: No such file or directory
```

**Comment by iamlemec** [comment]
This one can get a little tricky due to the possibility of spaces in filenames. But basically there are two ways in this case. With either method, you have to explicitly tell `xargs` to only treat newlines (and not spaces) and delimiters with `-d "\n"`, otherwise it'll break filenames with spaces into multiple items.

Method 1 is to use functionality in `mv` that allows you to operate on multiple files (the `-t` flag), in conjunction with plain `xargs`, as in:
``` zsh
echo "$files" | xargs -d "\n" mv -t "$dir"
```

Method 2 uses plain `mv` but tells `xargs` to only pass the files one at a time (the `-n` flag), as in
``` zsh
echo "$files" | xargs -n 1 -d "\n" mv "$dir"
```

Aand there's one more wrinkle because you're using OSX. They ship a weird version of `xargs`, so I would do `brew install findutils` and then replace `xargs` with `gxargs`.
